apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: qi-green
  namespace: qi
spec:
  selector:
    matchLabels:
      app: qi
      version: green
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: qi
        version: green
    spec:
      containers:
        - name: qi
          image: kanalavinodkumar/rollout:green # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster
---
kind: Service
apiVersion: v1
metadata: # Metadata of the resource kind we are creating
  name: qi
  namespace: qi
spec:
  selector:
    app: qi
    version: green
  type: NodePort
  ports:
  - name: http-port
    protocol: TCP
    # service-port
    port: 80
    # pod-port
    targetPort: 80